[package]
name = "cr_unescape"
version = "0.1.0"
authors = ["Sir. MaNiAl"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]